

function App() {

  const categories =  [
    "tv sarjat",
    "elokuvat",
    "lautapelit",
    "näyttelijät",
    "artistit",
    "bändit",
    "maat",
    "kaupungit",
    "joet",
    "järvet",
    "pääkaupungit",
    "festarit",
    "koirarodut",
    "kissarodut",
    "kotieläimet",
    "eläimet",
    "kalat",
    "meret",
    "kodinkoneet",
    "kaupat",
    "adjektiivit",
    "verbit",
    "substantiivit",
    "urheilulajit",
    "drinkit",
    "alkoholit",
    "juomapelit",
    "sarjakuvat",
    "marjat",
    "ammatit",
    "tieteelliset teoriat",
    "uskonnot",
    "lehdet",
    "kirjailijat",
    "pankit",
    "taivaankappaleet",
    "planeetat",
    "luonnonilmiöt",
    "nyrkkeilijät",
    "kasvisruoat",
    "einesruoat",
    "sukulaiset",
    "jalkapalloilijat",
    "koripalloilijat",
    "kilpailut",
    "jooga-asennot",
    "afrikan valtiot",
    "fobiat",
    "poliittiset puolueet",
    "asronautit",
    "aistit",
    "kaasut",
    "kiinalaiset ruoat",
    "intialaiset ruoat",
    "sarjamurhaajat",
    "naisten nimet",
    "miesten nimet",
    "nähhtävyydet",
    "saarivaltiot",
    "myrkyt",
    "tv sarjojen hahmot",
    "sarjakuvahahmot",
    "elokuvahahmot",
    "uskonnot",
    "kappaleet",
    "työkalut",
    "tietokonepelit",
    "ruokavaliot",
    "kukat",
    "tunturit",
    "korttipelit",
    "diktaattorit",
    "leikit",
    "poikabändit",
    "näytelmät",
    "raamatun henkilöt",
    "disney hahmot",
    "muodot",
    "salatut elämät hahmot",
    "politiikot",
    "suomalaiset artistit",
    "vihannekset",
    "automerkit",
    "säilykeruoat",
    "satuhahmot",
    "tietokoneen osat",
    "kouluaineet",
    "soittimet",
    "ideologiat",
    "ihmisen elimet",
    "ihmisen ruumiinosat",
    "shakkinappulat",
    "tosi-TV sarjat",
    "meikit",
    "filosofit",
    "kaupungit suomessa",
    "tanssiliikkeet",
    "tunnetut rikolliset",
    "toimintaelokuvat",
    "kauhuelokuvat",
    "energiajuomat",
    "kirjat",
    "karvattomat eläimet",
    "euroopan maat",
    "yrtit",
    "presidentit",
    "ajanvietteet",
    "jälkiruoat",
    "sijoituskohteet",
    "euroviisu kappaleet",
    "auton osat",
    "valuutat",
    "lastenlaulut",
    "kalevalan henkilöt",
    "sienet",
    "jumalat",
    "tieteenalat",
    "ravintolat",
    "aasian maat",
    "rikokset",
    "urheilujoukkueet",
    "taudit",
    "tarttuvat taudit",
    "roskaruoat",
    "pizzatäytteet",
    

  ]


  return (
    <div className="App">
       `<ul>{categories.map(cat =>
        <li>{cat}</li>)}
        </ul>`
    </div>
  );
}

export default App;
